xxxxxxxxxxxxxxxx
x--------x-x---x
xx---------x---x
x--x---------x-x
x--------------x
x--x-----------x
x--------------x
xx---x----x-x--x
x--xx----------x
x--------------x
xx--x----x--x--x
x--x---------xgx
x------x------xx
x-x--x---x-----x
x------1x------x
x----------x---x
x-----x-------xx
x-x------x--x--x
xxxxxxxxxxxxxxxx
